name: 'HubOMat'
description: 'Notarize & staple your Mac app.'

branding:
  icon: 'command'
  color: 'blue'

  # Example Usage:
  # - name: "Notarize & Staple"
  #   uses: hubomatic/hubomat@v0.0.19
  #   with:
  #     verbose: false
  #     timeout: 120 # minutes
  #     product-path: "Export/${{ env.APP_NAME }}.app"
  #     staple: true
  #     artifact-path: "Export/${{ env.APP_NAME }}.zip"
  #     team-id: ${{ secrets.TEAM_ID }}
  #     keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}
  #     certificate-data: ${{ secrets.DISTRIBUTION_CERTIFICATE_DATA }}
  #     certificate-passphrase: ${{ secrets.DISTRIBUTION_CERTIFICATE_PASSPHRASE }}
  #     appstore-connect-username: ${{ secrets.NOTARIZATION_USERNAME }}
  #     appstore-connect-password: ${{ secrets.NOTARIZATION_PASSWORD }}

inputs:
  verbose:
    description: "Verbose mode will print Notarization API responses."
    required: false
    default: false

  timeout:
    description: "The timeout in minutes for checking validation status."
    required: false
    default: 120

  workspace:
    description: 'Workspace'
    required: false
  project:
    description: 'Project'
    required: false
  scheme:
    description: 'Scheme'
    required: false
  configuration:
    description: 'Configuration'
    required: false
  archive-path:
    description: 'Archive path. If not specified will default to MainScheme.xcarchive'
    required: false

  export-path:
    description: "The export path for build artifacts."
    required: true

  temp-path:
    description: "Path to the temporary folder to use for intermediate artifacts."
    required: false
    default: "/tmp"
    
  product-path:
    description: "Path to the product to notarize."
    required: true

  export-method:
    description: "The method to use for export"
    required: false
    default: "developer-id"

  staple:
    description: "Whether to staple the notatized product."
    required: false
    default: true
    
  artifact-path:
    description: "Path to the notarized and stapled distribution zip."
    required: true
    
  certificate-data:
    description: 'Base64 encoded certificate in P12 format.'
    required: false
  certificate-path:
    description: 'Path to certificate in P12 format.'
    required: false
  certificate-passphrase:
    description: 'Passphrase to unlock the certificate P12 file. Required and cannot be empty.'
    required: true

  team-id:
    description: 'The signing team ID.'
    required: true

  keychain-name:
    description: 'Keychain name.'
    required: true
    default: "hubomatic-keychain"

  keychain-password:
    description: 'Keychain password (arbitrary).'
    required: true
    default: "hubomatic-keychain-password"
    
  appstore-connect-username:
    description: 'The AppStore Connect username.'
    required: false
  appstore-connect-password:
    description: 'The AppStore Connect application loader password (not the account password).'
    required: false

  appstore-connect-api-key:
    description: 'The AppStore Connect API Key.'
    required: false
  appstore-connect-api-issuer:
    description: 'The AppStore Connect API Issuer.'
    required: false

  primary-bundle-id:
    description: 'Unique identifier that identifies this product notarization. Defaults to the bundle identifier of the app you are uploading.'
    required: false

outputs:
  product-path:
    description: "Path to the product that was notarized"
  artifact-path:
    description: "Path to the stapled release artifact"

runs:
  using: 'node12'
  main: 'dist/index.js'

