<<<<<<< HEAD
name: 'HubOMat'
description: 'Distribute your Mac app.'

branding:
  icon: 'command'
  color: 'blue'

=======
name: 'Hello World'
description: 'Greet someone'
>>>>>>> 5832217 ('Checkpoint')
inputs:
  product-path:
    description: "Path to the product to notarize."
    required: true
<<<<<<< HEAD

  appstore-connect-username:
    description: 'The AppStore Connect username.'
    required: false
  appstore-connect-password:
    description: 'The AppStore Connect password.'
    required: false

  appstore-connect-api-key:
    description: 'The AppStore Connect API Key.'
    required: false
  appstore-connect-api-issuer:
    description: 'The AppStore Connect API Issuer.'
    required: false

  primary-bundle-id:
    description: 'Unique identifier that identifies this product notarization. Defaults to the bundle identifier of the app you are uploading.'
    required: false

  verbose:
    description: "Verbose mode will print Notarization API responses."
    required: false
    default: false

  timeout:
    description: "The timeout in minutes for checking validation status."
    required: false
    default: 120

outputs:
  product-path:
    description: "Path to the product that was notarized"

runs:
  using: 'node12'
  main: 'dist/index.js'
=======
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
    - run: ${{ github.action_path }}/goodbye.sh
      shell: bash
>>>>>>> 5832217 ('Checkpoint')
